python -u main_adv_eval_svhn.py \
    --data ../data \
    --dataset svhn \
    --data_number 1 \
    --arch resnet50 \
    --init $1 \
    --seed 1 \
    --batch_size 128 \
    --lr 0.01 \
    --weight_decay 5e-4 \
    --epochs 80 \
    --decreasing_lr 50,75 \
    --warmup 0 \
    --save_dir $2 \
    --tickets_file $3
