python -u main_std_eval.py \
    --data ../data \
    --dataset $1 \
    --arch resnet50 \
    --init $2 \
    --seed 1 \
    --batch_size 64 \
    --lr 0.001 \
    --weight_decay 5e-4 \
    --epochs 150 \
    --decreasing_lr 50,100 \
    --warmup 0 \
    --save_dir $3 \
    --tickets_file $4 
